### PR TITLE
[Update] Default Value Support + Hotfixes

### PR DESCRIPTION
**Pull request by ItsANoBrainer**
- Added support for default values for all input types
- Added all default value options to README
- Added password type example to README
- Fixed some CSS issues with select box
- Added scrollbar support for TALL inputs

### CODE REVIEW

**Comment by IdrisDose** [comment]
Has it been tested?

**Comment by ItsANoBrainer** [comment]
Yes, its apart of my large update to doorlocks here:
https://github.com/qbcore-framework/qb-doorlock/pull/79

I've used it to help easily create new doors back to back without having to type everything manually, like the old nui-doorlocks did. I've created over 65 configs for doorlock MLOs. Its wonderful.

**Comment by milotiro95** [comment]
You're right I was doing wrong I just change the configs/example.lua for a new one like 1 and it's working. I was trying to put no value in job / gang / citizenID / object.
Which perm can I use for everyone can use the door ?

**Review by FjamZoo — APPROVED** [review]
Been testing this for a hot minut, and no breaking changes are the autofill works like a charm.

**Pull request merged**
